Fix rustc/clippy warnings
webrtc-rs/webrtc pull request #384
Opened 2023-01-03 19:48 UTC by regexident

Before: 400 warnings
After: 6 warnings

2023-01-03 20:06 UTC, algesten requested changes
Major work! Thanks!

Some little niggly things I picked up on.

2023-01-03 20:06 UTC, algesten commented on sctp/src/association/association_test.rs
> +
Here

2023-01-03 20:06 UTC, algesten commented on sctp/src/timer/timer_test.rs
> +
yo

2023-01-03 20:06 UTC, algesten commented on webrtc/src/data_channel/data_channel_test.rs
> +
here

2023-01-03 20:06 UTC, algesten commented on webrtc/src/data_channel/data_channel_test.rs
> +                    panic!("Failed to send string on data channel");
This could be `.expect()`

2023-01-03 20:06 UTC, algesten commented on webrtc/src/data_channel/data_channel_test.rs
> +                    panic!("Failed to send string on data channel");
This could be `.expect()`

2023-01-03 21:54 UTC, regexident commented on dtls/src/conn/conn_test.rs
> -    }
No clue, tbh. My guess would be on documentation purposes?

2023-01-04 08:05 UTC, regexident commented on dtls/src/conn/conn_test.rs
> +                got_negotation_info = true;
Even, even nicer here is

```rust
let got_negotation_info = server_hello
    .extensions
    .iter()
    .any(|v| matches!(v, Extension::RenegotiationInfo(_)));
```

😄

2023-01-04 08:07 UTC, regexident commented on dtls/src/handshake/handshake_message_client_hello/handshake_message_client_hello_test.rs
> +            //Box::<CipherSuiteTLSEcdheEcdsaWithAes256CbcSha>::default(),
It resolves this clippy warning:
https://rust-lang.github.io/rust-clippy/master/#box_default

2023-01-04 08:11 UTC, regexident commented on interceptor/src/stats/interceptor.rs
> +
I added that to make it more obvious that the attribute applies to the entire scope (i.e. `#![…]`), not just the macro that follows (i.e. `#[…]`). The `!` is easy to miss while glancing over.

2023-01-04 08:14 UTC, regexident commented on interceptor/src/stats/interceptor.rs
> +
Also the existing module-scope `#![…]` directive blocks (~30) all are separated by a whitespace line. 🤔

2023-01-04 08:14 UTC, regexident commented on mdns/src/message/message_test.rs
> +
https://github.com/webrtc-rs/webrtc/pull/384#discussion_r1061222916

2023-01-04 08:14 UTC, regexident commented on rtp/benches/packet_bench.rs
> +
https://github.com/webrtc-rs/webrtc/pull/384#discussion_r1061222916

2023-01-04 08:14 UTC, regexident commented on rtp/src/codecs/h264/h264_test.rs
> +
https://github.com/webrtc-rs/webrtc/pull/384#discussion_r1061222916

2023-01-04 08:14 UTC, regexident commented on webrtc/src/data_channel/data_channel_test.rs
> +
https://github.com/webrtc-rs/webrtc/pull/384#discussion_r1061222916

2023-01-04 08:50 UTC, algesten commented on interceptor/src/stats/interceptor.rs
> +
Ok

2023-01-04 08:51 UTC, algesten commented
I've resolved the comments that I don't think need addressing.

2023-01-04 09:32 UTC, k0nserv reviewed
Great PR @regexident!

If we get to zero we could make CI enforce that

2023-01-04 09:32 UTC, k0nserv commented on dtls/src/handshake/handshake_message_client_hello/handshake_message_client_hello_test.rs
> +            //Box::<CipherSuiteTLSEcdheEcdsaWithAes256CbcSha>::default(),
Weird that it applies to commented out code 🤔

2023-01-04 10:25 UTC, regexident commented
> Great PR @regexident!
> 
> If we get to zero we could make CI enforce that

@k0nserv 💯 !

The remaining warnings are instances of `clippy::identity_op`.

1. `(1 << 16) | 0x0000`:

    https://github.com/webrtc-rs/webrtc/blob/958c0c44dc77f1f29ac3933b5b551b82aadff1e8/interceptor/src/report/receiver/receiver_test.rs#L429-L440

    Not even sure what this was supposed to do?

2. `(256u16 * 1 / 3) as u8`

    https://github.com/webrtc-rs/webrtc/blob/958c0c44dc77f1f29ac3933b5b551b82aadff1e8/interceptor/src/report/receiver/receiver_test.rs#L429-L440

    https://github.com/webrtc-rs/webrtc/blob/958c0c44dc77f1f29ac3933b5b551b82aadff1e8/interceptor/src/report/receiver/receiver_test.rs#L540-L551

    These ones should probably be changed to `(256u16 / 3) as u8`, I suppose?

3. `id * 1`

    https://github.com/webrtc-rs/webrtc/blob/958c0c44dc77f1f29ac3933b5b551b82aadff1e8/interceptor/src/twcc/sender/sender_test.rs#L39

    This one seems to be intentional for syntactical consistency, so putting a `#[allow(clippy::identity_op)]` in front of it seems like a reasonable approach.

2023-01-04 10:45 UTC, k0nserv commented
Unsure about **1**, your link for it is wrong.

**2** can just be `256 / 3` yes, alternatively as explained [here](https://www.rfc-editor.org/rfc/rfc3550#appendix-A.3) it's `(1 << 8) / 3` which yields the same thing but is more akin to what the spec says.

Agreed on **3**

2023-01-04 10:56 UTC, regexident commented
> Unsure about **1**, your link for it is wrong.

Fixed!

https://github.com/webrtc-rs/webrtc/blob/958c0c44dc77f1f29ac3933b5b551b82aadff1e8/interceptor/src/report/receiver/receiver_test.rs#L257-L268

> **2** can just be `256 / 3` yes, alternatively as explained [here](https://www.rfc-editor.org/rfc/rfc3550#appendix-A.3) it's `(1 << 8) / 3` which yields the same thing but is more akin to what the spec says.

Will make it `(1 << 8) / 3` then.

> Agreed on **3**

:+1:

2023-01-04 11:02 UTC, k0nserv commented
Ah, the high 16 bits are the number of cycles and the low 16 bits is the current sequence number, that's why **1** is written that way. I think we ignore the clippy error there too for the same reason as **3**.

2023-01-04 11:07 UTC, regexident commented
The warning is about the `… | 0x0000`, which has no effect.

And unlike #3 there doesn't seem to be any such pattern for the values provided to `last_sequence_number: …`, afaict.

2023-01-04 11:21 UTC, k0nserv commented
I think the `0x0000` bit is making it clear that we are setting both the high and low bits. We could send an extra packet with sequence number 1 in the test so it becomes

```rust
(1 << 16) | 0x0001
```

Clippy is right that it has no effect but it help with clarity to keep it this way I think, especially if we add a comment

2023-01-04 14:44 UTC, k0nserv approved these changes

2023-01-05 09:25 UTC, melekes approved these changes
![](https://media.giphy.com/media/ngWQUf0rrAvzvMbCET/giphy.gif)

2023-01-05 11:35 UTC, regexident commented
@algesten looks like it's stuck on your change request, which should all have been resolved. 🤔

2023-01-05 11:37 UTC, algesten approved these changes
Ship it! Great work!

2023-01-05 11:37 UTC, merged