Closing mdns agent
webrtc-rs/webrtc pull request #636
Opened 2024-11-20 12:32 UTC by ineiti

I use the library with many open/close, and I get mdns storms where the webrtc library searches for other nodes over the network in a very aggressive manner.

This has been proposed by @r-byondlabs, and might very well be the problem: if I open/close many connections, and the mdns-agents are not cleaned up, there might be many requests.

Fixes #616

2024-11-20 13:02 UTC, rainliu requested changes
Please fix the error

2024-11-20 23:45 UTC, rainliu commented
Cargo fmt warning

2024-11-21 07:05 UTC, ineiti commented
Here you go. With my version of cargo-fmt, it also changes the formatting of two other files. Let me know if that's OK.

I tested it on my setup, and the mdns-storms seem to be effectively gone, which is great!

I also added devbox and a pre-commit hook here: #637 . I'm a recent devbox-convert and really think it improves the contributor experience a lot.

2024-11-21 10:06 UTC, rainliu approved these changes

2024-11-21 10:06 UTC, merged